name: javascript actions

on: [push]
jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: Simple JS Action
        uses: http://github.com/actions/hello-world-javascript-action
        with:
          who-to-greet: John